In [1]:
import pandas as pd
import re

In [2]:
OVC_linelist = pd.read_csv('/Users/seyiabolarin/Downloads/Compiled BLL Q3.csv')

/var/folders/s0/wn3tsb5j0f33bv1nfqclc_tm0000gn/T/ipykernel_58920/654874292.py:1: DtypeWarning: Columns (2,4,23,24,26,27,28,29,32,33,36,40,47,53,54,57,58,59,60,61,62,64,65,66,67,68,69,70,71,72,73,74,75,76) have mixed types. Specify dtype option on import or set low_memory=False.
  OVC_linelist = pd.read_csv('/Users/seyiabolarin/Downloads/Compiled BLL Q3.csv')

In [3]:
# Group by State and Implementing Partner and count the clients
OVC_Info = OVC_linelist.groupby(['State ', 'IP']).size().reset_index(name='HH UID')

In [4]:
OVC_Info

         State         IP  HH UID
0       Adamawa  ICHSSA 4   21658
1     Akwa Ibom  ICHSSA 1   71919
2        Bauchi  ICHSSA 4   21187
3       Bayelsa  ICHSSA 1    3314
4         Borno  ICHSSA 3   13117
5   Cross River  ICHSSA 1   34836
6           Edo  ICHSSA 2    1614
7        Jigawa  ICHSSA 3    7577
8          Kano  ICHSSA 3   29308
9         Kebbi  ICHSSA 4    6883
10        Kwara  ICHSSA 2   11371
11        LAGOS  ICHSSA 2     411
12        Lagos  ICHSSA 2    1946
13        Niger  ICHSSA 3   29108
14       Sokoto  ICHSSA 4    8062
15       Taraba  ICHSSA 4    6692
16         Yobe  ICHSSA 3     346
17      Zamfara  ICHSSA 4    4379

In [5]:
# Save the filtered DataFrame to a new Excel file
OVC_Info.to_excel('Total_number_of_Households_by_State_By_IP.xlsx', index=False)

In [7]:
# Group by State and Implementing Partner and count the clients
OVC_Info_1 = OVC_linelist.groupby(['State ', 'IP','CBO']).size().reset_index(name='HH UID')

In [8]:
OVC_Info_1

,State,IP,CBO,HH UID
0,Adamawa,ICHSSA 4,Community Reach Initiative,5225
1,Adamawa,ICHSSA 4,Global Health and Social Awareness Foundation,2514
2,Adamawa,ICHSSA 4,Goggoji Zumunchi Development Initiative,6543
3,Adamawa,ICHSSA 4,Hope Rising Foundation,3584
4,Adamawa,ICHSSA 4,SPRING OF HOPE,3792
...,...,...,...,...
57,Sokoto,ICHSSA 4,HAKIMI COMMUNITY MOBILIZATION AND DEVELOPMENT ...,8062
58,Taraba,ICHSSA 4,Global Healthplus Public Initiative,3001
59,Taraba,ICHSSA 4,Women and Children Health Empowerment Foundation,3691
60,Yobe,ICHSSA 3,"Communal Conservation Friendly, Health and Soc...",346
61,Zamfara,ICHSSA 4,Voluntary Aid Initiative,4379

In [9]:
# Save the filtered DataFrame to a new Excel file
OVC_Info_1.to_excel('Total_number_of_Households_by_State_By_IP_by_CBO.xlsx', index=False)

In [11]:
OVC_HIV_Category = OVC_linelist['Curent HIV Status'].unique()

In [12]:
OVC_HIV_Category

array(['HIV Negative', 'HIV Positive', 'Unknown', 'Negative', 'Positive',
       'positive', 'POSITIVE', nan, 'Test not required based on HRA'],
      dtype=object)

In [13]:
OVC_HIV_Positive = OVC_linelist[OVC_linelist['Curent HIV Status'].isin(['HIV Positive', 'Positive','positive','POSITIVE'])]

In [14]:
# Group by State and Implementing Partner and count the clients
OVC_HIV_Positive_HH = OVC_HIV_Positive.groupby(['State ', 'IP']).size().reset_index(name='HH UID')

In [15]:
OVC_HIV_Positive_HH

         State         IP  HH UID
0       Adamawa  ICHSSA 4    1774
1     Akwa Ibom  ICHSSA 1    4931
2        Bauchi  ICHSSA 4    1775
3       Bayelsa  ICHSSA 1     463
4         Borno  ICHSSA 3     527
5   Cross River  ICHSSA 1    2441
6           Edo  ICHSSA 2    1614
7        Jigawa  ICHSSA 3     254
8          Kano  ICHSSA 3    1492
9         Kebbi  ICHSSA 4     855
10        Kwara  ICHSSA 2     853
11        LAGOS  ICHSSA 2     411
12        Lagos  ICHSSA 2    1946
13        Niger  ICHSSA 3    1680
14       Sokoto  ICHSSA 4     857
15       Taraba  ICHSSA 4    2401
16         Yobe  ICHSSA 3     106
17      Zamfara  ICHSSA 4     513

In [16]:
OVC_HIV_Positive_HH.to_excel('OVC_HIV_Positive_Household.xlsx', index = False)